---
- name: Show running config on the node
  eos_command:
    commands: show run
  change_when: false
  register: res

- name: Dump the configuration
  copy:
    dest: "{{ _bacup_filepath }}"
    content: |
      {{ res.stdout }}
  delegate_to: localhost

# vim:sw=2:ts=2:et:
