---
dependency:
  name: galaxy
driver:
  name: delegated
lint:
  name: yamllint
platforms:
  # .. seealso:: ../../tests/inventory/juniper_vlabs/hosts
  - name: vmx01

# .. seealso::
# https://molecule.readthedocs.io/en/stable/configuration.html#id22
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    links:
      hosts: ../../tests/inventory/juniper_vlabs/hosts
      group_vars: ../../tests/inventory/juniper_vlabs/group_vars
      host_vars: ../../tests/inventory/juniper_vlabs/host_vars
verifier:
  name: ansible
  lint:
    name: ansible-lint

# vim:sw=2:ts=2:et:
